# List of mappings to/from GitHub & GitLab
[[mappings]]
github_repo = "brndnmtthws/labhub"
gitlab_repo = "brndnmtthws-oss/labhub"
[[mappings]]
github_repo = "brndnmtthws/conky"
gitlab_repo = "brndnmtthws-oss/conky"
