apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "labhub.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "labhub.name" . }}
    helm.sh/chart: {{ include "labhub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "labhub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "labhub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LABHUB_TOML
              value: "/etc/labhub/LabHub.toml"
            - name: LABHUB_REPO_MAPPING_TOML
              value: "/etc/labhub/LabHub-repo-mapping.toml"
            {{- with .Values.envVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: labhub-ssh-keys
              mountPath: "/etc/ssh-keys"
              readOnly: true
            - name: labhub
              mountPath: "/etc/labhub"
              readOnly: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /check
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /check
              port: http
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: labhub-ssh-keys
          secret:
            secretName: labhub-ssh-keys
        - name: labhub
          configMap:
            name: {{ template "labhub.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
